import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  scrollContainer: {
    flex: 1,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 20,
  },
  temperatureContainer: {
    alignItems: "center",
    marginVertical: 20,
    padding: 20,
    borderRadius: 10,
    backgroundColor: "#f5f5f5",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    width: "100%",
  },
  temperature: {
    fontSize: 48,
    fontWeight: "bold",
    marginBottom: 10,
  },
  tempInRange: {
    color: "#2ecc71",
  },
  tempOutOfRange: {
    color: "#e74c3c",
  },
  description: {
    fontSize: 16,
    marginBottom: 10,
    color: "#555",
  },
  message: {
    fontSize: 16,
    color: "#555",
    marginVertical: 20,
  },
  errorMessage: {
    fontSize: 16,
    color: "#e74c3c",
    marginVertical: 20,
  },
  refreshButton: {
    backgroundColor: "#2ecc71",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 5,
    marginVertical: 10,
    width: "100%",
    alignItems: "center",
  },
  configButton: {
    backgroundColor: "#3498db",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 5,
    marginVertical: 10,
    width: "100%",
    alignItems: "center",
  },
  buttonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 16,
  },
  tokenContainer: {
    width: "100%",
    marginVertical: 10,
  },
  tokenInput: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 5,
    padding: 10,
    fontSize: 16,
    width: "100%",
  },
  saveButton: {
    backgroundColor: "#2ecc71",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
  },
  tokenButtonsContainer: {
    width: "100%",
  },
  clearButton: {
    backgroundColor: "#e74c3c",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 5,
    marginVertical: 10,
    width: "100%",
    alignItems: "center",
  },
  lastUpdated: {
    fontSize: 12,
    color: "#777",
    marginBottom: 15,
  },
  rangeContainer: {
    width: "100%",
    marginVertical: 10,
  },
  rangeInputRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  rangeLabel: {
    fontSize: 16,
    width: 50,
  },
  rangeInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 5,
    padding: 10,
    fontSize: 16,
  },
  rangeInfo: {
    fontSize: 14,
    color: "#555",
    marginBottom: 5,
  },
  rangeStatus: {
    fontSize: 16,
    fontWeight: "bold",
  },
  inRangeText: {
    color: "#2ecc71",
  },
  outOfRangeText: {
    color: "#e74c3c",
  },
  // Debug section styles
  debugButton: {
    backgroundColor: "#9b59b6",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 5,
    marginVertical: 10,
    width: "100%",
    alignItems: "center",
  },
  debugContainer: {
    width: "100%",
    marginTop: 20,
    padding: 15,
    backgroundColor: "#f8f9fa",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ddd",
  },
  debugTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 15,
    color: "#333",
  },
  debugSubtitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#333",
  },
  debugActionButton: {
    backgroundColor: "#3498db",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 5,
    marginVertical: 8,
    width: "100%",
    alignItems: "center",
  },
  statusContainer: {
    marginVertical: 10,
    padding: 10,
    backgroundColor: "#fff",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#eee",
    width: "100%",
  },
  debugText: {
    fontSize: 14,
    color: "#333",
    marginBottom: 5,
  },
  logsContainer: {
    marginTop: 15,
    width: "100%",
  },
  logsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  smallButton: {
    backgroundColor: "#7f8c8d",
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 3,
    marginLeft: 5,
  },
  smallButtonText: {
    color: "white",
    fontSize: 12,
  },
  logEntry: {
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    marginBottom: 5,
  },
  logTimestamp: {
    fontSize: 12,
    color: "#7f8c8d",
    marginBottom: 3,
  },
  logMessage: {
    fontSize: 14,
    color: "#333",
  },
  // Background task management styles
  buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginVertical: 10,
  },
  smallActionButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 5,
    flex: 1,
    marginHorizontal: 5,
    alignItems: "center",
  },
  registerButton: {
    backgroundColor: "#27ae60",
  },
  unregisterButton: {
    backgroundColor: "#c0392b",
  },
}); 